#!/bin/bash

INSTALL_PYTHON_DEPS=$1
if [ "$INSTALL_PYTHON_DEPS" != "true" ]; then
    pip install rticonnextdds-connector
    echo "Skipping python deps install"
    exit 0
fi

echo -e "\e[93mInstalling Python Dependencies\e[0m"

pip install rticonnextdds-connector \
    robotpy==2022.4.8 \
    robotpy[ctre] \
    robotpy[all] \
    robotpy[commands2] \
    robotpy[navx] \
    wpilib==2022.4.1.6
