#!/usr/bin/bash
restart() {
    echo "Restarting..."
    cd ~/offseason2023/
    docker compose restart
}

log() {
    echo "Logging..."
    cd ~/offseason2023/
    if [ "$1" == "N" ]; then
        echo "Not Following logs..."
        docker compose logs
        exit 0
    fi
    echo "Following logs..."
    docker compose logs -f
}

jetson-kill() {
    echo "Killing..."
    cd ~/offseason2023/
    docker compose kill
}

stop() {
    echo "Stopping..."
    cd ~/offseason2023/
    docker compose stop
}

edit() {
    echo "Editing..."
    cd ~/offseason2023/
    nano docker-compose.yml
}

help() {
    echo "Usage:"
    echo "  edit    -- Opens the docker compose file in nano"
    echo "  log     -- Outputs the docker compose logs"
    echo "  restart -- Restarts docker container"
    echo "  stop    -- Stops docker containers"
    echo "  kill    -- Kills docker containers"
    echo "  ps      -- Same as docker ps"
    echo "  "
    echo ""
    echo "Usage: jetson (edit | restart | stop | kill | log | ps)"
}

case $1 in 
    "restart")
        case $2 in
            "--help")
                help
            ;;

            "-h")
                help
            ;;

            *)
                restart
            ;;
        esac
    ;;

    "help")
        case $2 in
            "--help")
                help
            ;;

            "-h")
                help
            ;;

            *)
                help
            ;;
        esac
    ;;

    "log")
        case $2 in
            "--help")
                help
            ;;

            "-h")
                help
            ;;

            "-n")
                log "N"
            ;;

            *)
                log "Y"
            ;;
        esac
    ;;

    "kill")
        case $2 in
            "--help")
                help
            ;;

            "-h")
                help
            ;;

            *)
                jetson-kill
            ;;
        esac
    ;;

    "stop")
        case $2 in
            "--help")
                help
            ;;

            "-h")
                help
            ;;

            *)
                stop
            ;;
        esac
    ;;

    "edit")
        case $2 in
            "--help")
                help
            ;;

            "-h")
                help
            ;;

            *)
                edit
            ;;
        esac
    ;;

    "ps")
        docker ps $2
    ;;
    
    *)
        echo "Unknown option: \"$1\""
        help
        ;;
esac